### ISSUE TITLE
Blank TWP2 window bug

### ISSUE THREAD

**Issue by ezsnackeur** [Nazfib/TransferWindowPlanner2#1]
![image](https://github.com/user-attachments/assets/065a2068-9126-4520-a893-9b7ede1710ab)
![image](https://github.com/user-attachments/assets/55e88854-0fd5-403e-ab4e-1ecc8678a3ad)
this error keeps getting thrown as long as the TWP2 window is open in the blank state

to reproduce select a vessel as target for TWP2 in tracking station or KSC scene and plot the transfer, then enter vab and open the TWP2 window again, it will be in this blank state.
I think its related to the fact that you cant target vessels from the VAB but only celestial bodies.

**Comment by ezsnackeur** [comment]
![image](https://github.com/user-attachments/assets/4a7b4ede-9c84-4fdf-9aab-9130d187963d)
clicking show vessels from VAB doesnt make anything appear

**Comment by Nazfib** [comment]
Thanks, you've indeed found a bug. I've published a new preview release with a fix.

**Comment by ezsnackeur** [comment]
yayy number 1! :v
